django_workshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import HttpResponseRedirect, reverse

urlpatterns = [
    url(r'^$', lambda request: HttpResponseRedirect(reverse('blog'))),
	url(r'^', include('workshop.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^workshop/', include('workshop.urls'))
]

workshop/urls.py
from django.conf.urls import url
from workshop.views import blog_view, get_blog_json, add_post_view#, BlogView

urlpatterns = [
    #url(r'^$', BlogView.as_view(), name='blog'),
	url(r'^$', blog_view, name='blog'),
	url(r'add/$', add_post_view, name='add-post'),
	url(r'blog_json/$', get_blog_json, name="get-blog-json")
]

workshop/models.py
from django.db import models

class Post(models.Model):
	class Meta:
		verbose_name = 'Post'
		verbose_name_plural = 'Posts'
		unique_together = ('title', 'content', 'author')

	title = models.CharField(max_length=255, blank=False, null=False)
	content = models.TextField()
	author = models.CharField(max_length=255, blank=False, null=False)
	date = models.DateTimeField(auto_now=False, null=False, blank=False)

	def __str__(self):
		return ', '.join([self.title, self.author, str(self.date)])

workshop/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
	class Meta:
		model = Post
		fields = '__all__'

	def __init__(self, *args, **kwargs):
		super(PostForm, self).__init__(*args, **kwargs)

workshop/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView
from django.http import JsonResponse
from .models import Post
from .forms import PostForm

'''
class BlogView(TemplateView):

    model = Post
    template_name = 'blog.html'

    def get_context_data(self, **kwargs):
        context = super(BlogView, self).get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-date')

        if (len(post_list) > 0):
            context['post_list'] = [
								({
									'title': post.title,
									'content': post.content,
									'author': post.author,
									'date': post.date
								})
								for post in post_list
								]
        else:
            context['error'] = 'Nessun post trovato'
        return context
'''

def blog_view(request):
	context = {}
	post_list = Post.objects.all().order_by('-date')

	if (len(post_list) > 0):
		context['post_list'] = [
							({
								'title': post.title,
								'content': post.content,
								'author': post.author,
								'date': post.date
							})
							for post in post_list
							]
	else:
		context['error'] = 'Nessun post trovato'
	return render(request, 'blog.html', context)


def get_blog_json(request):
	blog = {}
	post_list = Post.objects.all().order_by('-date')
	cont = 0

	if (len(post_list) > 0):
		for post in post_list:
			blog[cont] = {
				'title': post.title,
				'content': post.content,
				'author': post.author,
				'date': post.date
			}
			cont += 1
	else:
		blog['error'] = "Nessun post trovato"
	return JsonResponse(blog)


def add_post_view(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('blog')
		else:
			args = {'form':form}
			return render(request, 'add_post.html', args)
	else:
		form = PostForm()
		args = {'form':form}
		return render(request, 'add_post.html', args)

templates/add_post.html
{% extends "base.html" %}
{% load static %}
{% block title %} <title>MyBlog | HOMEPAGE</title> {% endblock %}

{% block content %}
	<br>
	<div class="container">
		<h3 class="center-align">Aggiungi Post</h3>
		<div class="row">
			<form class="col s12" method='post'>
				{% csrf_token %}
				{{ form.as_table }}
				<button class="waves-effect waves-light btn-large col s10 m10 l4 offset-s1 offset-m1 offset-l4 red" type="submit">SALVA</button>
			</form>
			<!--<form class="col s12" method='post'>
		        {% csrf_token %}
		        <div class="row">
		            <div class="col s12">
		                {{ form.title.errors }}
		                <div class="input-field col s12">
		                    <label for="id_title">{{ form.title.label }}</label>
		                    {{ form.title }}
		                </div>
		            </div>
		        </div>
		        <br />
		        <div class="row">
		            <div class="col s12">
		                {{ form.content.errors }}
		                <div class="input-field col s12">
		                    <label for="id_content">{{ form.content.label }}</label>
		                    {{ form.content }}
		                </div>
		            </div>
		        </div>
		        <br />
		        <div class="row">
		            <div class="col s12">
		                {{ form.author.errors }}
		                <div class="input-field col s12">
		                    <label for="id_author">{{ form.author.label }}</label>
		                    {{ form.author }}
		                </div>
		            </div>
		        </div>
		        <br />
		        <div class="row">
		            <div class="col s12">
		                {{ form.date.errors }}
		                <div class="input-field col s12">
		                    <label for="id_date">{{ form.date.label }}</label>
		                    {{ form.date }}
		                </div>
		            </div>
		        </div>
		        <button class="waves-effect waves-light btn-large col s10 m10 l4 offset-s1 offset-m1 offset-l4 red" type="submit">SALVA</button>
		    </form>-->
		</div>
	</div>
{% endblock %}

{% block script %}
	<script type="text/javascript">
		$(document).ready(function() {
			$('textarea').addClass('materialize-textarea');
			$('#id_date').attr('placeholder', 'yyyy-mm-dd hh:mm:ss');
		});
	</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block title %}{% endblock %}

        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        {% block style %}{% endblock %}
    </head>
    <body class="grey darken-4">
		<header class="container-fluid valign-wrapper teal white-text">
			<h2 class="center-align">MYBLOG</h2>
		</header>
        <main>
            {% block content %}{% endblock %}
		</main>

		<footer class="page-footer teal">
		<div class="container">
          <div class="row">
            <div class="col l12 m12 s12">
              <h4>ITIS G. Marconi Verona</h4>
              DJANGO WORKSHOP
            </div>
          </div>
        </div>
          <div class="footer-copyright teal darken-2">
            <div class="container">
            Emanuele Feola, Tonin Davide
            </div>
          </div>
        </footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
        {% block script %}{% endblock %}
    </body>
</html>

templates/blog.html
{% extends "base.html" %}
{% load static %}
{% block title %} <title>MyBlog | HOMEPAGE</title> {% endblock %}

{% block content %}
	<br />
	<div class="container">
		<div class="row">
		  	<a class="waves-effect waves-light btn-large col s10 m10 l4 offset-s1 offset-m1 offset-l4 orange" href="{% url 'add-post' %}">Aggiungi Post</a>
		</div>
		<!-- Lista dei blog -->
		<div class="row">
			{% if error != null %}
				<div class='row'>
					<h4 class='col s12 text-center red-text'>{{ error }}</h4>
				</div>
			{% else %}
				{% for post in post_list %}
					<div class="row">
						<div class="col s12 m12 l12">
						  <div class="card">
							<div class="card-content">
							  <span class="card-title center-align">{{ post.title }}</span>
							  <p class="post-content">{{ post.content }}</p>
							</div>
							<div class="card-action">
							  <p>{{ post.author}}, {{ post.date }}</p>
							</div>
							</div>
						</div>
					  </div>

				{% endfor %}
			{% endif %}
		</div>
	</div>

{% endblock %}